irb/urls.py
from django.urls import path
from . import views
app_name = 'irb'

urlpatterns = [
   path('home/', views.irb_dashboard, name='irb_dashboard'),
   path('approvals/',views.irb_approvals, name ='irb_approvals'),
   path('minutes',views.irb_minutes, name = 'irb_minutes_of_meeting'),
   path('irb_approve/<int:pk>', views.irb_approve, name='irb_approved'),
   path('irb_modified/<int:pk>', views.irb_modified, name='irb_modified'),

]

project/urls.py
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [
    path('', views.display_form1,name= 'project'),
    path('edit/',views.edit_form1,name = 'edit'),
    path('project/<int:id>', views.project_view, name='view'),
    path('re', views.display_form2, name='project2'),

]

secretariat/urls.py
from django.urls import path
from . import views
app_name = 'secretariat'

urlpatterns =[
    path('secretariat/home/', views.secretariat_dashboard, name='secretariat_dashboard'),
    path('secretariat/profile/', views.secretariat_profile, name='secretariat_profile'),
    path('secretariat/director_review/', views.secretariat_director_review, name='secretariat_director_review'),
    path('secretariat/irb_review/', views.secretariat_irb_review, name='secretariat_irb_review'),
    path('secretariat/final_review/', views.secretariat_final_review, name='secretariat_final_review'),
    path('secretariat/updatedr/<int:pk>',views.upstatdr,name='update_statusdr'),
    path('secretariat/updateirb/<int:pk>', views.upstatdr, name='update_statusirbr'),
    path('secretariat/updatefinr/<int:pk>', views.upstatdr, name='update_statusdfinr'),
    path('secretariat/email/<int:pk>',views.email,name='send_email')
]

untitled300/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import routing_logic

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('dashboard/', include('dashboard.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('guide/', include('guide.urls')),
    path('director/', include('director.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('irb/', include('irb.urls')),

    # only use this path for testing purpose
    path('project/', include('project.urls')),

    path('users/', include('django.contrib.auth.urls')),
    path('', routing_logic, name='routing_logic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/secretariat_dashboard/modify.html
<!DOCTYPE html>
<html>
<style type="text/css">
body {
  font-family: Arial, sans-serif;
  <---!background: url(http://www.shukatsu-note.com/wp-content/uploads/2014/12/computer-564136_1280.jpg) no-repeat;-->
  background-size: cover;
  height: 100vh;
}

h1 {
  text-align: center;
  font-family: Tahoma, Arial, sans-serif;
  color: #06D85F;
  margin: 80px 0;
}

.box {
  width: 40%;
  margin: 0 auto;
  background: rgba(255,255,255,0.2);
  padding: 35px;
  border: 2px solid #fff;
  border-radius: 20px/50px;
  background-clip: padding-box;
  text-align: center;
}

.button {
  font-size: 1em;
  padding: 10px;
  color: #fff;
  border: 2px solid #06D85F;
  border-radius: 20px/50px;
  text-decoration: none;
  cursor: pointer;
  transition: all 0.3s ease-out;
}
.button:hover {
  background: #06D85F;
}

.overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;
}
.comment_box
{
  margin: 70px auto;
  padding: 20px;
  background: #ecf0f1;
  border-radius: 20px;
  width: 80%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: #333;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}
textarea{
background :#ecfof1;
}
p{
font-color: #000000;
}
@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }

}
</style>
<body>
<h1>Modify form</h1>
<div class="box">
	<a class="button" href="#popup1">comment here</a>
</div>
<div class="popup">
<div id="popup1" class="overlay">
<div class="comment_box">
<form action="mailto:myemail@domain.com" method="post">
<p>Comments and suggestions:<br><textarea name="comments" rows="10" cols="150"></textarea><br>
<input type="submit" value="Send email" align="center"></p>
</form>
</div>
</div>
</div>
</body>
</html>

templates/secretariat_dashboard/sec_dashboard.html
{% extends 'sec_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
<h1>Welcome to Secretariat Dashboard</h1>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Projects</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Project Code</th>
                          <th style="width: 20%">Project Name</th>
                          <th style="width: 20%">Researcher</th>
                          <th style="width: 20%">Guide Name</th>
                          <th>Status</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                         {% for object in project %}
                             <tr>
                                 <td>{{ object.stud_id.student_id.id }}</td>
                                 <td>{{ object.project_title }}</td>
                                 <td>{{ object.stud_id.student_id.name }}</td>
                                 <td>{{ object.PI_id.principal_id.name }}</td>
                                 <td>{{ object.stud_id.get_st_project_status_display}}</td>
                               <td><a href="{% url 'secretariat:send_email' object.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Send Email </a></td>

                             </tr>
                            {% endfor %}
                      <tr><td>Suchita</td></tr>
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/secretariat_dashboard/sec_director_review.html
{% extends 'sec_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Director Review</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Student ID</th>
                          <th style="width: 15%">Student Name</th>
                          <th style="width: 15%">Student Project</th>
                          <th style="width: 15%">Action</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for object in project %}
                        {% if object.stud_id.st_project_status == 2 %}
                        <tr>
                          <td>{{ object.stud_id.student_id.id }}</td>
                          <td>
                            <a>{{ object.stud_id.student_id.name }}</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>{{ object.project_title }}</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="{% url 'secretariat:update_statusdr' object.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approved </a>

</td>
                          <td>
                            <a href="{% url 'project:view' object.id %}" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        {% endif %}
{% endfor %}
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/secretariat_dashboard/sec_final_review.html
{% extends 'sec_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Final Review</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Projects</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Student ID</th>
                          <th style="width: 15%">Student Name</th>
                          <th style="width: 15%">Student Project</th>
                          <th style="width: 15%">Investigator Name</th>
                          <th style="width: 15%">Action</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>101</td>
                          <td>
                            <a>Untitled</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>Team Encipher</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>
                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        <tr>
                          <td>101</td>
                          <td>
                            <a>Untitled</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>Team Encipher</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>

                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        <tr>
                          <td>101</td>
                          <td>
                            <a>Untitled</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>Team Encipher</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>

                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        <tr>
                          <td>101</td>
                          <td>
                            <a>Untitled</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>Team Encipher</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>

                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        <tr>
                          <td>101</td>
                          <td>
                            <a>Untitled</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>Team Encipher</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>
                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/secretariat_dashboard/sec_irb_review.html
{% extends 'sec_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>IRB Review</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Projects</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Student ID</th>
                          <th style="width: 15%">Student Name</th>
                          <th style="width: 15%">Student Project</th>
                          <th style="width: 15%">Investigator Name</th>
                          <th style="width: 15%">Action</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
{% for object in project %}
                        {% if object.stud_id.st_project_status == 7 %}
                        <tr>
                          <td>{{ object.stud_id.student_id.id }}</td>
                          <td>
                            <a>{{ object.stud_id.student_id.name }}</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>{{ object.project_title }}</td>

                            <td>Hinduja Hospital</td>
    <td>                            <a href="{% url 'secretariat:update_statusirbr' object.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Forward </a>

</td>
                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        {% endif %}
{% endfor %}
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}