director/urls.py
from django.urls import path
from . import views
app_name = 'director'

urlpatterns = [
    path('director/home/', views.director_dashboard, name='director_dashboard'),
    path('director/profile/', views.director_profile, name='director_profile'),
    path('director/student_details/', views.director_student_details, name='director_student_details'),
    path('director/project_details/', views.director_project_details, name='director_project_details'),
    path('director/guide_details/', views.director_guide_details, name='director_guide_details'),
    path('director/secretariat_details/', views.director_secretariat_details, name='director_secretariat_details'),
    path('director/project_approval/', views.project_approval, name='project_approval'),
    path('director/approved/<pk>', views.project_approved, name='director_approve'),
    path('director/modfied/<pk>', views.project_modified, name='director_modify'),

]

irb/urls.py
from django.urls import path
from . import views
app_name = 'irb'

urlpatterns = [
   path('home/', views.irb_dashboard, name='irb_dashboard'),
   path('approvals/',views.irb_approvals, name ='irb_approvals'),
   path('minutes',views.irb_minutes, name = 'irb_minutes_of_meeting'),
   path('irb_approve/<int:pk>', views.irb_approve, name='irb_approved'),
   path('irb_modified/<int:pk>', views.irb_modified, name='irb_modified'),

]

project/urls.py
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [
    path('', views.display_form1,name= 'project'),
    path('edit/',views.edit_form1,name = 'edit'),
    path('project/<int:id>', views.project_view, name='view'),
    path('re', views.display_form2, name='project2'),

]

untitled300/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import routing_logic

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('dashboard/', include('dashboard.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('guide/', include('guide.urls')),
    path('director/', include('director.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('irb/', include('irb.urls')),

    # only use this path for testing purpose
    path('project/', include('project.urls')),

    path('users/', include('django.contrib.auth.urls')),
    path('', routing_logic, name='routing_logic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/director_dashboard/director_dashboard.html
{% extends 'director_sidebar.html' %}
{% load staticfiles %}
{% block content %}
{% block headers %}
    <link rel="stylesheet" href="{% static 'progess.css' %}">

{% endblock %}
<h1>Welcome to Director Dashboard</h1>
<br>
<br>
<div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="card" style="background-color:#57889c;">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-1">
                                        <i class="pe-7s-study" style="color:white;"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text" style="color:white;"><span class="count">8652</span></div>
                                            <div class="stat-heading" style="color:white;">Students</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<!--
                    <div class="col-lg-3 col-md-6">
                        <div class="card" style="background-color:#D6A2E8;">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-2">
                                        <i class="pe-7s-note2" style="color:white;"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text" style="color:white;"><span class="count">3435</span></div>
                                            <div class="stat-heading" style="color:white;">Projects</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    -->
                    <div class="col-lg-3 col-md-6">
                        <div class="card" style="background-color:#686de0;">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-1">
                                        <i class="pe-7s-note2" style="color:white;"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text" style="color:white;"><span class="count">11664</span></div>
                                            <div class="stat-heading" style="color:white;">Projects</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="card" style="background-color:#353b48;">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-1">
                                        <i class="pe-7s-users" style="color:white;"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text" style="color:white;"><span class="count">2356</span></div>
                                            <div class="stat-heading" style="color:white;">Guides</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="card" style="background-color:#d1b993;">
                            <div class="card-body">
                                <div class="stat-widget-five">
                                    <div class="stat-icon dib flat-color-1">
                                        <i class="pe-7s-science" style="color:white;"></i>
                                    </div>
                                    <div class="stat-content">
                                        <div class="text-left dib">
                                            <div class="stat-text" style="color:white;"><span class="count">23569</span></div>
                                            <div class="stat-heading" style="color:white;">Topics</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
</div>

    {% endblock %}

templates/director_dashboard/director_guide_details.html
{% extends 'director_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3> Guide</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>  Guides</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">  Guide ID</th>
                          <th style="width: 20%"> Guide Name</th>
                          <!--<th style="width: 20%"> Guide Project</th>-->
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                       {% for p in pi %}
                      <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>
                            <a>{{ p.principal_id }}</a>
                            <br/>
                          </td>
                          <td>
                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        {% endfor %}
                                              </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/director_dashboard/director_profile.html
{% extends 'director_sidebar.html' %}


{% load staticfiles %}

{% block headers %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Professor Profile | Kiaalap - Kiaalap Admin Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

{% endblock %}
{% block content %}

<h1>Welcome to Director Profile</h1>
        <!-- Single pro tab review Start-->
        <div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="profile-info-inner">
                            <div class="profile-img">
                                <img src="{% static 'images/user2.jpg' %}" alt="" />
                            </div>
                            <div class="profile-details-hr">
                                <div class="row">
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr">
                                            <p><b>Name</b><br />{{ user.username }}</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                            <p><b>Designation</b><br /> {{ dir.designation }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr">
                                            <p><b>Email ID</b><br />{{ user.email }}</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                            <p><b>Phone</b><br />{{ user.contact }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <div class="product-payment-inner-st res-mg-t-30 analysis-progrebar-ctn">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Activity</a></li>
                                <li><a href="#reviews"> Biography</a></li>
                                <li><a href="#INFORMATION">Update Details</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-tab-list tab-pane fade" id="INFORMATION">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <input name="number" type="text" class="form-control" placeholder="First Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Last Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Address">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Date of Birth">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Department">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="number" class="form-control" placeholder="Pincode">
                                                        </div>
                                                        <div class="file-upload-inner ts-forms">
                                                            <div class="input prepend-big-btn">
                                                                <label class="icon-right" for="prepend-big-btn">
																	</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="form-group sm-res-mg-15 tbpf-res-mg-15">
                                                            <input type="text" class="form-control" placeholder="Description">
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																<option>Select Gender</option>
																<option>Male</option>
																<option>Female</option>
															</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select country</option>
																	<option>India</option>
																	<option>Pakistan</option>
																	<option>Amerika</option>
																	<option>China</option>
																	<option>Dubai</option>
																	<option>Nepal</option>
																</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select state</option>
																	<option>Gujarat</option>
																	<option>Maharastra</option>
																	<option>Rajastan</option>
																	<option>Maharastra</option>
																	<option>Rajastan</option>
																	<option>Gujarat</option>
																</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select city</option>
																	<option>Surat</option>
																	<option>Baroda</option>
																	<option>Navsari</option>
																	<option>Baroda</option>
																	<option>Surat</option>
																</select>
                                                        </div>
                                                        <input type="number" class="form-control" placeholder="Mobile no.">
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="payment-adress mg-t-15">
                                                            <button type="submit" class="btn btn-primary waves-effect waves-light mg-b-15">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/jquery.meanmenu.js' %}"></script>
    <!-- tab JS
		============================================ -->
    <script src="{% static 'js/tab.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/director_dashboard/director_project_approval.html
{% extends 'director_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Director Review</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Student ID</th>
                          <th style="width: 15%">Student Name</th>
                          <th style="width: 15%">Student Project</th>
                          <th style="width: 15%">Action</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for object in project %}
                        {% if object.stud_id.st_project_status == 3 %}
                        <tr>
                          <td>{{ object.stud_id.student_id.id }}</td>
                          <td>
                            <a>{{ object.stud_id.student_id.name }}</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>{{ object.project_title }}</td>

                            <td>Hinduja Hospital</td>
    <td>
        <a href="{% url 'director:director_approve' object.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Approve </a>
        <a href="{% url 'director:director_modify' object.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i> Modify </a>

    </td>
                          <td>
                            <a href="{% url 'project:view' object.id %}" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>
                          </td>
                        </tr>
                        {% endif %}
{% endfor %}
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/director_dashboard/director_project_details.html
{% extends 'director_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
<h1>Welcome to Director Project Details</h1>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Projects</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Projects</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <p>Simple table with project listing with progress and editing options</p>

                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Project Code</th>
                          <th style="width: 20%">Project Name</th>
                          <th style="width: 20%">Researcher</th>
                          <th style="width: 20%">Guide Name</th>
                          <th>Status</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
                         {% for object in project %}
                             <tr>
                                 <td>{{ object.stud_id.student_id.id }}</td>
                                 <td>{{ object.project_title }}</td>
                                 <td>{{ object.stud_id.student_id.name }}</td>
                                 <td>{{ object.PI_id.principal_id.name }}</td>
                                 <td>{{ object.stud_id.get_st_project_status_display}}</td>
                                 <td><a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a></td>
                             </tr>
                            {% endfor %}
                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}