director/urls.py
from django.urls import path
from . import views
app_name = 'director'

urlpatterns = [
    path('director/home/', views.director_dashboard, name='director_dashboard'),
    path('director/profile/', views.director_profile, name='director_profile'),
    path('director/student_details/', views.director_student_details, name='director_student_details'),
    path('director/project_details/', views.director_project_details, name='director_project_details'),
    path('director/guide_details/', views.director_guide_details, name='director_guide_details'),
    path('director/secretariat_details/', views.director_secretariat_details, name='director_secretariat_details'),
    path('director/project_approval/', views.project_approval, name='project_approval'),
    path('director/approved/<pk>', views.project_approved, name='director_approve'),
    path('director/modfied/<pk>', views.project_modified, name='director_modify'),

]

guide/urls.py
from django.urls import path
from . import views
app_name = 'guide'

urlpatterns = [
    path('guide/home/', views.guide_dashboard, name='guide_dashboard'),
    path('guide/profile/', views.guide_profile, name='guide_profile'),
    path('guide/student/', views.guide_student, name='guide_student'),
    path('guide/initreview/<int:pk>', views.initreview,name='initreview'),
    path('guide/interreview/<int:pk>', views.interreview, name='interreview'),
    path('guide/finalreview/<int:pk>', views.finalreview, name='finalreview'),
    path('guide/initmodify/<int:pk>', views.initmodifychanges, name='initmodify'),
    path('guide/intermodify/<int:pk>', views.intermodifychanges, name='intermodify'),

]

irb/urls.py
from django.urls import path
from . import views
app_name = 'irb'

urlpatterns = [
   path('home/', views.irb_dashboard, name='irb_dashboard'),
   path('approvals/',views.irb_approvals, name ='irb_approvals'),
   path('minutes',views.irb_minutes, name = 'irb_minutes_of_meeting'),
   path('irb_approve/<int:pk>', views.irb_approve, name='irb_approved'),
   path('irb_modified/<int:pk>', views.irb_modified, name='irb_modified'),

]

project/urls.py
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [
    path('', views.display_form1,name= 'project'),
    path('edit/',views.edit_form1,name = 'edit'),
    path('project/<int:id>', views.project_view, name='view'),
    path('re', views.display_form2, name='project2'),

]

student/urls.py
from django.urls import path, include

from student.views import routing_logic
from . import views


app_name = 'student'
urlpatterns = [
    path('',routing_logic, name = 'route'),
    path('home/', views.student_dashboard, name='student_dashboard'),
    path('profile/', views.student_profile, name='student_profile'),
    path('budget/', include('budget.urls'), name='student_budget'),
    path('documents/', views.viewdocuments, name='student_documents'),
    path('upload_documents/', views.uploadDocuments, name= 'student_documents_upload'),
    path('project_details/', views.student_project_details, name='student_project_details'),
    path('completion_report/', views.student_completion_report, name='student_completion_report'),
    path('inc/', views.sample, name='sample'),

]

untitled300/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import routing_logic

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('dashboard/', include('dashboard.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('guide/', include('guide.urls')),
    path('director/', include('director.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('irb/', include('irb.urls')),

    # only use this path for testing purpose
    path('project/', include('project.urls')),

    path('users/', include('django.contrib.auth.urls')),
    path('', routing_logic, name='routing_logic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/director_sidebar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block headfiles %}
{% block headers %}
{% endblock %}
{% endblock %}

            {% block sidebar %}
                    <li class="active">
                        <img src="{% static 'images/femaleuser.jpg' %}" alt="Logo" style="border-radius:50%;">
                    </li>
                    <li class="active">
                        <a href="{% url 'director:director_dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:director_profile' %}" class="dropdown-toggle" > <i class="menu-icon fa  fa-address-card"></i>Director Profile</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:project_approval' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-wpforms"></i> Project Approvals</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:director_project_details' %}" class="dropdown-toggle"> <i class="menu-icon fa fa-list"></i>All Project Details</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:director_student_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-cogs"></i>Student Details</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:director_guide_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Guide Details</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'director:director_secretariat_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-wpforms"></i>Secretariat Details</a>
                    </li>

            {% endblock %}

{% block content %}

<h1>Welcome to my Profile</h1>

{% endblock %}

templates/guide_sidebar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block headfiles %}
{% block headers %}
{% endblock %}
{% endblock %}

            {% block sidebar %}
                    <li class="active">
                        <img src="{% static 'images/femaleuser.jpg' %}" alt="Logo" style="border-radius:50%;">
                    </li>
                    <li class="active">
                        <a href="{% url 'guide:guide_dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'guide:guide_profile' %}" class="dropdown-toggle" > <i class="menu-icon fa  fa-address-card"></i>Guide Profile</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'guide:guide_student' %}" class="dropdown-toggle"> <i class="menu-icon fa fa-list"></i>Student Details</a>
                    </li>

            {% endblock %}

{% block content %}

<h1>Welcome to my Profile</h1>

{% endblock %}

templates/irb_sidebar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block headfiles %}
{% block headers %}
{% endblock %}
{% endblock %}

            {% block sidebar %}
                    <li class="active">
                        <img src="{% static 'images/femaleuser.jpg' %}" alt="Logo" style="border-radius:50%;">
                    </li>
                    <li class="active">
                        <a href="{% url 'irb:irb_dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'irb:irb_approvals' %}" class="dropdown-toggle" > <i class="menu-icon fa  fa-address-card"></i>Approval</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'irb:irb_minutes_of_meeting' %}" class="dropdown-toggle"> <i class="menu-icon fa fa-list"></i>Minutes of meeting</a></li>
{#                    </li>#}
{#                    <li class="menu-item-has-children dropdown">#}
{#                        <a href="{% url 'director:director_student_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-cogs"></i>Student Details</a>#}
{#                    </li>#}
{#                    <li class="menu-item-has-children dropdown">#}
{#                        <a href="{% url 'director:director_guide_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Guide Details</a>#}
{#                    </li>#}
{#                    <li class="menu-item-has-children dropdown">#}
{#                        <a href="{% url 'director:director_secretariat_details' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-wpforms"></i>Secretariat Details</a>#}
{#                    </li>#}
            {% endblock %}

{% block content %}

{% endblock %}

templates/sec_sidebar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block headfiles %}
{% block headers %}
{% endblock %}
{% endblock %}

            {% block sidebar %}
                    <li class="active">
                        <img src="{% static 'images/maleuser.png' %}" alt="Logo" style="border-radius:50%;">
                    </li>
                    <li class="active">
                        <a href="{% url 'secretariat:secretariat_dashboard' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'secretariat:secretariat_profile' %}" class="dropdown-toggle"> <i class="menu-icon fa  fa-address-card"></i>Secretariat Profile</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'secretariat:secretariat_director_review' %}" class="dropdown-toggle"> <i class="menu-icon fa fa-list"></i>Director Review</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'secretariat:secretariat_irb_review' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-cogs"></i>IRB Review</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'secretariat:secretariat_final_review' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Final Review</a>
                    </li>
            {% endblock %}

{% block content %}

<h1>Welcome to my Profile</h1>

{% endblock %}

templates/student_sidebar.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block headfiles %}
{% block headers %}
{% endblock %}
{% endblock %}


            {% block sidebar %}
                    <li class="active">
                        <img src="{% static 'images/maleuser.png' %}" alt="Logo" style="border-radius:50%;height:190px;margin-left: 20px;">
                    </li>
                    <li class=" dropdown">
                        <div style="padding:10px; font-size:20px;"><center>{{user}}</center></div>
                    </li>
                    <li class="active">
                        <a href="{% url 'student:student_dashboard' %} "><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'student:student_profile' %}" class="dropdown-toggle"> <i class="menu-icon fa  fa-address-card"></i>Student Profile</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'student:student_project_details' %}" class="dropdown-toggle"> <i class="menu-icon fa fa-list"></i>Project Details</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'student:student_completion_report' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-wpforms"></i>Completion Report</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                   <a href="{% url 'student:budget:addform' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Budget form</a>
                    </li>
                 <li class="menu-item-has-children dropdown">
                   <a href="{% url 'project:project2' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Submission form 2</a>
                    </li>
                 <li class="menu-item-has-children dropdown">
                   <a href="{% url 'student:budget:term' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-money"></i>Term Extension Form</a>
                    </li>
                    <li class="menu-item-has-children dropdown">
                        <a href="{% url 'student:student_documents' %}" class="dropdown-toggle" > <i class="menu-icon fa fa-wpforms"></i>Documents</a>
                    </li>
            {% endblock %}

{% block content %}

<h1>Welcome to my Profile</h1>

{% endblock %}