guide/urls.py
from django.urls import path
from . import views
app_name = 'guide'

urlpatterns = [
    path('guide/home/', views.guide_dashboard, name='guide_dashboard'),
    path('guide/profile/', views.guide_profile, name='guide_profile'),
    path('guide/student/', views.guide_student, name='guide_student'),
    path('guide/initreview/<int:pk>', views.initreview,name='initreview'),
    path('guide/interreview/<int:pk>', views.interreview, name='interreview'),
    path('guide/finalreview/<int:pk>', views.finalreview, name='finalreview'),
    path('guide/initmodify/<int:pk>', views.initmodifychanges, name='initmodify'),
    path('guide/intermodify/<int:pk>', views.intermodifychanges, name='intermodify'),

]

irb/urls.py
from django.urls import path
from . import views
app_name = 'irb'

urlpatterns = [
   path('home/', views.irb_dashboard, name='irb_dashboard'),
   path('approvals/',views.irb_approvals, name ='irb_approvals'),
   path('minutes',views.irb_minutes, name = 'irb_minutes_of_meeting'),
   path('irb_approve/<int:pk>', views.irb_approve, name='irb_approved'),
   path('irb_modified/<int:pk>', views.irb_modified, name='irb_modified'),

]

project/urls.py
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [
    path('', views.display_form1,name= 'project'),
    path('edit/',views.edit_form1,name = 'edit'),
    path('project/<int:id>', views.project_view, name='view'),
    path('re', views.display_form2, name='project2'),

]

untitled300/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import routing_logic

urlpatterns = [
    path('admin/', admin.site.urls),
#   path('dashboard/', include('dashboard.urls')),
    path('users/', include('users.urls')),
    path('student/', include('student.urls')),
    path('guide/', include('guide.urls')),
    path('director/', include('director.urls')),
    path('secretariat/', include('secretariat.urls')),
    path('irb/', include('irb.urls')),

    # only use this path for testing purpose
    path('project/', include('project.urls')),

    path('users/', include('django.contrib.auth.urls')),
    path('', routing_logic, name='routing_logic'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/guide_dashboard/guide_dashboard.html
{% extends 'guide_sidebar.html' %}

{% block content %}

<h1>Welcome to Guide Dashboard</h1>

{% endblock %}

templates/guide_dashboard/guide_profile.html
{% extends 'guide_sidebar.html' %}


{% load staticfiles %}

{% block headers %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Professor Profile | Kiaalap - Kiaalap Admin Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

{% endblock %}
{% block content %}

<h1>Welcome to Guide Profile</h1>
        <!-- Single pro tab review Start-->
        <div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                        <div class="profile-info-inner">
                            <div class="profile-img">
                                <img src="{% static 'images/user2.jpg' %}" alt="" />
                            </div>
                            <div class="profile-details-hr">
                                <div class="row">
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr">
                                            <p><b>Name</b><br /> Fly Zend</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                            <p><b>Designation</b><br /> Head of Dept.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr">
                                            <p><b>Email ID</b><br /> fly@gmail.com</p>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                        <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                            <p><b>Phone</b><br /> +01962067309</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="address-hr">
                                            <p><b>Address</b><br /> E104, catn-2, Chandlodia Ahmedabad Gujarat, UK.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                        <div class="product-payment-inner-st res-mg-t-30 analysis-progrebar-ctn">
                            <ul id="myTabedu1" class="tab-review-design">
                                <li class="active"><a href="#description">Activity</a></li>
                                <li><a href="#reviews"> Biography</a></li>
                                <li><a href="#INFORMATION">Update Details</a></li>
                            </ul>
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-tab-list tab-pane fade" id="INFORMATION">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <input name="number" type="text" class="form-control" placeholder="First Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Last Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Address">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Date of Birth">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="text" class="form-control" placeholder="Department">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="number" class="form-control" placeholder="Pincode">
                                                        </div>
                                                        <div class="file-upload-inner ts-forms">
                                                            <div class="input prepend-big-btn">
                                                                <label class="icon-right" for="prepend-big-btn">
																	</label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="form-group sm-res-mg-15 tbpf-res-mg-15">
                                                            <input type="text" class="form-control" placeholder="Description">
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																<option>Select Gender</option>
																<option>Male</option>
																<option>Female</option>
															</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select country</option>
																	<option>India</option>
																	<option>Pakistan</option>
																	<option>Amerika</option>
																	<option>China</option>
																	<option>Dubai</option>
																	<option>Nepal</option>
																</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select state</option>
																	<option>Gujarat</option>
																	<option>Maharastra</option>
																	<option>Rajastan</option>
																	<option>Maharastra</option>
																	<option>Rajastan</option>
																	<option>Gujarat</option>
																</select>
                                                        </div>
                                                        <div class="form-group">
                                                            <select class="form-control">
																	<option>Select city</option>
																	<option>Surat</option>
																	<option>Baroda</option>
																	<option>Navsari</option>
																	<option>Baroda</option>
																	<option>Surat</option>
																</select>
                                                        </div>
                                                        <input type="number" class="form-control" placeholder="Mobile no.">
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="payment-adress mg-t-15">
                                                            <button type="submit" class="btn btn-primary waves-effect waves-light mg-b-15">Submit</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="{% static 'js/jquery.meanmenu.js' %}"></script>
    <!-- tab JS
		============================================ -->
    <script src="{% static 'js/tab.js' %}"></script>
    <!-- main JS
		============================================ -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/guide_dashboard/guide_project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/guide_dashboard/guide_student.html
{% extends 'guide_sidebar.html' %}
{% load staticfiles %}
{% block content %}
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
  </head>
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">


              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-sm-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Students</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li class="dropdown">
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">


                    <!-- start project list -->
                    <table class="table table-striped projects">
                      <thead>
                        <tr>
                          <th style="width: 1%">Student ID</th>
                          <th style="width: 15%">Student Name</th>
                          <th style="width: 15%">Project Title</th>
                          <th style="width: 15%">Initial Check</th>
                          <th style="width: 15%">Intermediate Check</th>
                          <th style="width: 15%">Final Check</th>
                          <th style="width: 20%"></th>
                        </tr>
                      </thead>
                      <tbody>
{#                        <tr>#}
{#                          <td>101</td>#}
{#                          <td>#}
{#                            <a>Untitled</a>#}
{#                            <br />#}
{#                            <small>Due Date 01.01.2015</small>#}
{#                          </td>#}
{#                            <td>Team Encipher</td>#}
{#                             #}
{#                            <td>Hinduja Hospital</td>#}
{#    <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>#}
{#                            <a href="#" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>#}
{#</td>#}
{#                                <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>#}
{#                            <a href="#" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>#}
{#</td>#}
{#                                <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>#}
{#                            <a href="#" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>#}
{#</td>#}
{#                            #}
{#                          <td>#}
{#                            <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>#}
{#                          </td>#}
{#                        </tr>#}
{% for key in project %}
 <tr>
                          {# <td>101</td> #}
                            <td>
                            <a>{{ key.stud_id.id}}</a>
                          </td>
                          <td>
                            <a>{{ key.stud_id.student_id.name }}</a>
                            <br />
                            <small>Due Date 01.01.2015</small>
                          </td>
                            <td>
                            <a>{{key.project_title }}</a>
                          </td>

    <td>
        {% if key.stud_id.st_project_status == 1 %}
            <a href="{% url 'guide:initreview' key.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>
            <a href="{% url 'guide:initmodify' key.stud_id.id %}" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>
        {% endif %}
        {% if key.stud_id.st_project_status > 1 %}
            <a href="#" class="btn btn-success btn-sm" disabled> Done </a>
        {% endif %}

</td>

<td>
        {% if key.stud_id.st_project_status == 7 %}
            <a href="{% url 'guide:interreview' key.stud_id.id %}" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>
            <a href="{% url 'guide:intermodify' key.stud_id.id %}" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>
        {% endif %}
        {% if key.stud_id.st_project_status > 7 %}
            <a href="#" class="btn btn-success btn-sm" disabled> Done </a>
        {% endif %}
</td>
                                <td>                            <a href="#" class="btn  btn-info btn-sm"><i class="fa fa-folder"></i>  Approve </a>
                            <a href="#" class="btn btn-warning btn-sm"><i class="fa fa-folder"></i> Modify </a>
</td>

                          <td>
                            <a href="{% url 'project:view' key.id %}" class="btn btn-primary btn-sm"><i class="fa fa-folder"></i> View </a>

                          </td>
                        </tr>
{% endfor %}

                      </tbody>
                    </table>
                    <!-- end project list -->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/guide_dashboard/modify.html
<!DOCTYPE html>
<html>
<style type="text/css">
body {
  font-family: Arial, sans-serif;
  <---!background: url(http://www.shukatsu-note.com/wp-content/uploads/2014/12/computer-564136_1280.jpg) no-repeat;-->
  background-size: cover;
  height: 100vh;
}

h1 {
  text-align: center;
  font-family: Tahoma, Arial, sans-serif;
  color: #06D85F;
  margin: 80px 0;
}

.box {
  width: 40%;
  margin: 0 auto;
  background: rgba(255,255,255,0.2);
  padding: 35px;
  border: 2px solid #fff;
  border-radius: 20px/50px;
  background-clip: padding-box;
  text-align: center;
}

.button {
  font-size: 1em;
  padding: 10px;
  color: #fff;
  border: 2px solid #06D85F;
  border-radius: 20px/50px;
  text-decoration: none;
  cursor: pointer;
  transition: all 0.3s ease-out;
}
.button:hover {
  background: #06D85F;
}

.overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;
}
.comment_box
{
  margin: 70px auto;
  padding: 20px;
  background: #ecf0f1;
  border-radius: 20px;
  width: 80%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: #333;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}
textarea{
background :#ecfof1;
}
p{
font-color: #000000;
}
@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }

}
</style>
<body>
<h1>Modify form</h1>
<div class="box">
	<a class="button" href="#popup1">comment here</a>
</div>
<div class="popup">
<div id="popup1" class="overlay">
<div class="comment_box">
<form action="mailto:myemail@domain.com" method="post">
<p>Comments and suggestions:<br><textarea name="comments" rows="10" cols="150"></textarea><br>
<input type="submit" value="Send email" align="center"></p>
</form>
</div>
</div>
</div>
</body>
</html>